-- institution_narratives_schema.sql
-- Pre-encoded institutional narratives for the JENNI intelligence layer.
-- Lives in institution_quant.db (derived/analytical layer).
--
-- narrative_type values:
--   'identity'          -- stable institutional facts: control, Carnegie, location, founding
--   'financial_profile' -- financial health snapshot from institution_quant (auto-refreshed per seeder run)
--   'stress_signal'     -- pre-computed stress signal language from financial_stress_signals
--   'enrollment_profile'-- enrollment trajectory and dynamics
--   'peer_context'      -- peer group positioning and caveats
--   'athletics'         -- EADA athletics profile
--   'governance'        -- board composition and governance policy flags
--
-- source values:
--   'auto_seeded'       -- generated from structured data by narrative_seeder.py
--   'hand_crafted'      -- written and verified by a human analyst; highest trust
--   'model_generated'   -- generated by Claude during a session (lower stability)
--
-- Model receives narratives marked [pre-encoded] — stable facts, not real-time interpretation.
-- confidence: 'high' | 'medium' | 'low'
-- valid_from / valid_until: survey_year bounds (NULL = always valid / indefinite)

CREATE TABLE IF NOT EXISTS institution_narratives (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    unitid          INTEGER NOT NULL,
    narrative_type  TEXT    NOT NULL,
    content         TEXT    NOT NULL,
    confidence      TEXT    NOT NULL DEFAULT 'medium',
    valid_from      INTEGER,
    valid_until     INTEGER,
    source          TEXT    NOT NULL DEFAULT 'auto_seeded',
    formula_version TEXT             DEFAULT '1.0',
    last_verified   TEXT             DEFAULT (date('now')),
    created_at      TEXT             DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_narr_unitid      ON institution_narratives (unitid);
CREATE INDEX IF NOT EXISTS idx_narr_type        ON institution_narratives (narrative_type);
CREATE INDEX IF NOT EXISTS idx_narr_unitid_type ON institution_narratives (unitid, narrative_type);
CREATE INDEX IF NOT EXISTS idx_narr_source      ON institution_narratives (source);
